version: '3.8'

services:
  backend:
    build:
      context: ./server/newproject
    ports:
      - "8000:8000"
    volumes:
      - ./server/newproject:/app
    environment:
      - ALLOWED_HOSTS=*
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client/app
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000